# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

---
APPLY_FIXES: all
DISABLE:
  - COPYPASTE
  - DOCKERFILE
  - REPOSITORY
  - SPELL
DISABLE_LINTERS:
  - MAKEFILE_CHECKMAKE
  - PYTHON_PYLINT
PLUGINS:
  - https://raw.githubusercontent.com/cdzombak/mega-linter-plugin-dockerfilelint/main/mega-linter-plugin-dockerfilelint/dockerfilelint.megalinter-descriptor.yml

MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--disable MD013"

VALIDATE_ALL_CODEBASE: true
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
